[project]
name = "pythonicml"
version = "0.1.0"
description = "Compare inference performance between Python and Rust using small-scale models"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.7.0",
    "transformers>=4.52.4",
]
